### PR TITLE
Add Clasp support

### PR DESCRIPTION
**Pull request by Bike**
Various minor concerns:

- dunno about copyright
- dynamic-extent concerns we already discussed
- I didn't do the thing that reads the definition from from the file if available
- I assumed that "if available" meant that the various frame readers should return `nil` if there's no good information
- function names may be things like strings (for C++ functions) or non-fbound names (like `(lambda (x))` or `(flet foo)`)
- I don't know what the `pos` of frames is for, so here it'll be the position in the actual call stack, which will often differ from the frame's position in the list returned by `stack` due to hidden system frames
- there don't seem to be readers for information like the source info of the call (rather than the function being called)

### CODE REVIEW

**Comment by Shinmera** [comment]
Yeah, the Dissect protocol needs to be re-examined and documented much better. I can't say I see any obvious disagreements right now about what you mentioned.

**Comment by Shinmera** [comment]
Please do add a file header though. You can leave out the copyright line, something like:
```
#|
 This file is a part of Dissect
 Author: Bike <bike@whatever>
|#
```

**Comment by Bike** [comment]
There you go.

**Comment by Shinmera** [comment]
Thank you!

**Pull request merged**
